#!/usr/bin/env python3

from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys


DIRECT_TEXT_SIZES = {
    10, 11, 12, 13, 14, 15, 17, 20, 24,
}

# These are the actual system-ui companion pixel heights the demos request when
# the primary UI font falls back from DejaVu Sans to the CJK font path.
COMPANION_TEXT_SIZES = {
    15, 16, 17, 18, 20, 22, 25, 26, 29, 31, 35,
}

STRING_RE = re.compile(r'"([^"\\]*(?:\\.[^"\\]*)*)"')


def collect_source_files(root: pathlib.Path) -> list[pathlib.Path]:
    files = sorted(root.glob("demo_*.uya"))
    ddz_dir = root / "doudizhu"
    files.extend(sorted(ddz_dir.rglob("*.uya")))
    return files


def collect_codepoints(root: pathlib.Path) -> list[int]:
    chars = {code for code in range(0x20, 0x7F)}
    for path in collect_source_files(root):
        text = path.read_text(encoding="utf-8")
        for match in STRING_RE.finditer(text):
            literal = match.group(1)
            for ch in literal:
                code = ord(ch)
                if code >= 0x20:
                    chars.add(code)
    return sorted(chars)


def write_codepoints(path: pathlib.Path, codepoints: list[int]) -> None:
    lines = [f"{code:04X}\n" for code in codepoints]
    path.write_text("".join(lines), encoding="ascii")


def write_manifest(path: pathlib.Path, codepoints: list[int], sizes: list[int]) -> None:
    lines = [
        "# Generated by tools/gen_wqy_demo_bitmap_assets.py\n",
        f"glyph_count={len(codepoints)}\n",
        f"sizes={','.join(str(size) for size in sizes)}\n",
    ]
    path.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--generator", required=True)
    parser.add_argument("--font", required=True)
    parser.add_argument("--examples-root", default="gui/examples")
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    out_dir = pathlib.Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    codepoints = collect_codepoints(pathlib.Path(args.examples_root))
    sizes = sorted(DIRECT_TEXT_SIZES | COMPANION_TEXT_SIZES)

    glyphs_path = out_dir / "wqy_microhei_demo_glyphs.txt"
    manifest_path = out_dir / "wqy_microhei_demo_manifest.txt"
    write_codepoints(glyphs_path, codepoints)
    write_manifest(manifest_path, codepoints, sizes)

    cmd = [
        args.generator,
        "--font",
        args.font,
        "--glyphs",
        str(glyphs_path),
        "--out-dir",
        str(out_dir),
    ]
    for size in sizes:
        cmd.extend(["--size", str(size)])

    subprocess.run(cmd, check=True)
    print(f"wrote {glyphs_path} ({len(codepoints)} glyphs)")
    print(f"wrote {manifest_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
